#!/usr/sbin/nft -f

flush ruleset

define LAN_NET = 192.168.69.0/24

table inet devops_filter {

        set lan_tcp_ports {
                type inet_service
                elements = { 22, 80, 8080 }
        }

        chain input {
                type filter hook input priority filter; policy drop;

                iifname "lo" counter accept
                ct state established,related counter accept

                ip saddr $LAN_NET tcp dport @lan_tcp_ports counter accept
        }
}
