#!/usr/sbin/nft -f

flush ruleset

define MGMT_NET = 10.10.10.0/24
define SERVER_NET = 10.20.20.0/24

table inet devops_filter {

    set ssh_sources {
        type ipv4_addr
        flags interval
        elements = { $MGMT_NET, $SERVER_NET }
    }

    chain input {
        type filter hook input priority filter; policy drop;

        iifname "lo" counter accept
        ct state established,related counter accept

        ip protocol icmp counter accept

        ip saddr @ssh_sources tcp dport 22 counter accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
